name: Build and Publish Docker Images

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - 'README.md'
      - 'screenshot.png'
      - 'Taskfile.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push vjik/dev-php:8.3
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:image/dev"
          push: true
          build-args: |
            PHP_VERSION=8.3
          tags: vjik/dev-php:8.3
